In [ ]:
NumPy stands for Numerical Python.
NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [ ]:
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions
that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

In [ ]:
Table of content:
1/ A list, tuple or any array-like object into the array() method, narray
2/ numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
3/ Accessing: array indexing, negative indexing, slicing
	integer indexing, boolean Array Indexing
4/ NaN (Not a Number), ~np.isnan(a)
	np.iscomplex(a)
5/ Data Types in NumPy, dtype, np.dtype
Converting Data Type on Existing Arrays: astype()
6/ Shape of an Array: shape, reshape
7/ Copy (Deep Copy), View (Shallow Copy), No Copy (=)
	Reshape returns View
8/ Array Iterating, nditer(), ndenumerate(), Modifying Array Values, External Loop (optional), Broadcasting Iteration
9/ Array Manipulation
	Transpose Operations
	Joining Array: concatenate(), stack(), hstack(), vstack(), dstack()
	Splitting Array: array_split(), hsplit()
	Adding / Removing Elements: resize, append, insert, delete, unique
10/ Searching: where(), extract(), nonzero() , numpy.argmax() & numpy.argmin(),
11/ Sort: searchsorted(), side='right', argsort(), lexsort()
12/ F

In [ ]:
# ndarray Object (N-dimensional array)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

In [ ]:
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, 
# and it will be converted into an ndarray
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

In [ ]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
import numpy as np

arr = np.array(42)

print(arr)

In [ ]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [ ]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors
# => NumPy has a whole sub module dedicated towards matrix operations called numpy.mat
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

In [ ]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

In [ ]:
# Check Number of Dimensions?
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [ ]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
1	
object

Any object exposing the array interface method returns an array, or any (nested) sequence.

2	
dtype

Desired data type of array, optional

3	
copy

Optional. By default (true), the object is copied

4	
order

C (row major) or F (column major) or A (any) (default)

5	
subok

By default, returned array forced to be a base class array. If true, sub-classes passed through

6	
ndmin

Specifies minimum dimensions of resultant array

In [ ]:
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 1) 
print(a)

In [ ]:
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, 
# and it will be converted into an ndarray
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


In [ ]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
import numpy as np

arr = np.array(42)

print(arr)


In [ ]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


In [ ]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors
# => NumPy has a whole sub module dedicated towards matrix operations called numpy.mat
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


In [ ]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


In [ ]:
# Check Number of Dimensions?
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


In [ ]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
1	
object

Any object exposing the array interface method returns an array, or any (nested) sequence.

2	
dtype

Desired data type of array, optional

3	
copy

Optional. By default (true), the object is copied

4	
order

C (row major) or F (column major) or A (any) (default)

5	
subok

By default, returned array forced to be a base class array. If true, sub-classes passed through

6	
ndmin

Specifies minimum dimensions of resultant array


In [ ]:
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 1) 
print(a)


In [ ]:
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

In [ ]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


In [ ]:
NumPy Array Indexing


In [ ]:
# Access 2-D Arrays

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('\n2nd element on 1st dim: ', arr[0, 1])


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('5th element on 2nd dim: ', arr[1, 4])


In [ ]:
# Access 3-D Arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr, '\n')
print(arr[0, 1, 2])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


In [ ]:
# Negative Slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


In [ ]:
# STEP
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a)
print(s)
print(a[s])

In [ ]:
# Slicing 2-D Arrays
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr,'\n')
print(arr[0:2, 2])

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr, '\n')
print(arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:')
print(a[...,1]) 
print('\n')  

# Now we will slice all items from the second row 
print('The items in the second row are:') 
print(a[1,...]) 
print('\n')  

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[...,1:])



In [ ]:
Advanced Indexing

In [ ]:
Integer Indexing

In [ ]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x)
print('\n')
y = x[[0,1,2], [0,1,0]] 
print(y)

In [3]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:') 
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [4]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:') 
print(x) 
print('\n')

# slicing 
z = x[1:4,1:3] 

print('After slicing, our array becomes:')
print(z) 
print('\n')  

# using advanced index for column 
y = x[1:4,[1,2]] 

print('Slicing using advanced index for column:') 
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


In [ ]:
Boolean Array Indexing

In [ ]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:')
print(x) 
print('\n')  

# Now we will print the items greater than 5 
print('The items greater than 5 are:')
print(x[x > 5])


In [ ]:
# NaN (Not a Number) elements are omitted by using ~ (complement operator)
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)])

In [ ]:
import numpy as np 
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])
print(a[~np.iscomplex(a)])


In [ ]:
Data Types in NumPy

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


In [ ]:
Creating Arrays With a Defined Data Type


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

In [ ]:
# For i, u, f, S and U we can define size as well.

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')
# #int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc.
print(arr)
print(arr.dtype)

In [ ]:
1	
bool_

Boolean (True or False) stored as a byte

2	
int_

Default integer type (same as C long; normally either int64 or int32)

3	
intc

Identical to C int (normally int32 or int64)

4	
intp

Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5	
int8

Byte (-128 to 127)

6	
int16

Integer (-32768 to 32767)

7	
int32

Integer (-2147483648 to 2147483647)

8	
int64

Integer (-9223372036854775808 to 9223372036854775807)

9	
uint8

Unsigned integer (0 to 255)

10	
uint16

Unsigned integer (0 to 65535)

11	
uint32

Unsigned integer (0 to 4294967295)

12	
uint64

Unsigned integer (0 to 18446744073709551615)

13	
float_

Shorthand for float64

14	
float16

Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15	
float32

Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16	
float64

Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17	
complex_

Shorthand for complex128

18	
complex64

Complex number, represented by two 32-bit floats


In [ ]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

In [ ]:
# dtype of array is now float32 (4 bytes) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x.itemsize)


In [ ]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')


In [ ]:
the use of structured data type
the field name and the corresponding scalar data type is to be declared.

# dtype()


In [ ]:
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(dt)
print(a)
print(a['age'])

In [5]:
import numpy as np 

student = np.dtype([('name','S5'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(student)
print(a)
print(a['name'])
print(a['age'])
print(a['marks'])

[('name', 'S5'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[b'abc' b'xyz']
[21 18]
[50. 75.]


In [ ]:
#Not important
The byte order is decided by prefixing '<' or '>' to data type.
'<' means that encoding is little-endian (least significant is stored in smallest address).
'>' means that encoding is big-endian (most significant byte is stored in smallest address).



In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


In [ ]:
# Shape of an Array
NumPy arrays have an attribute called shape that returns
a tuple with each index having the number of corresponding elements.


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr, '\n')
print(arr.shape)

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [16]:
# reshape
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
print(a, '\n')
a.shape = (3,2) 
print(a)


[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print('id(a): ',id(a))
b = a.reshape(3,2) 
print(b)
print('id(b): ',id(b))
print('b is a? ', b is a )

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)


In [ ]:
The Difference Between copy() and view()

The main difference between a copy and a view of an array is that the copy is a new array,
and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array,
and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array,
and any changes made to the original array will affect the view.



In [ ]:
# COPY
# Deep Copy
# The ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data,
# and doesn’t share with the original array.
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(id(arr))
print(x)
print(id(x))

x.shape = (2, 3)
print('arr:\n', arr)
print('x:\n', x)



In [20]:
# VIEW
# Shallow Copy
# ndarray.view() method which is a new array object that looks at the same data of the original array.
# Change in dimensions of the new array doesn’t change dimensions of the original.

import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(id(arr))
print(x)
print(id(x))

x.shape = (2, 3)
print('arr:\n', arr)
print('x:\n', x)


[42  1  2  3  4  5]
2253295592144
[42  1  2  3  4  5]
2253295591952
arr:
 [42  1  2  3  4  5]
x:
 [[42  1  2]
 [ 3  4  5]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)


In [7]:
import numpy as np 
# To begin with, a is 3X2 array 
a = np.arange(6).reshape(3,2) 

print('Array a:')
print (a)  

print('Create view of a:') 
b = a.view() 
print(b)  

print('id() for both the arrays are different:') 
print('id() of a:')
print(id(a))  
print('id() of b:') 
print(id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

# b[0,0] = 8
# a[2,1] = 9

print('Shape of b:') 
print(b)  

print('Shape of a:') 
print(a)

print('a.base:\n',a.base)
print('b.base:\n',b.base)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
1651773256400
id() of b:
1651773188976
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]
a.base:
 [0 1 2 3 4 5]
b.base:
 [0 1 2 3 4 5]


In [21]:
# Check if Array Owns it's Data
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # The copy returns None.
print(y.base) # The view returns the original array.

None
[1 2 3 4 5]


In [8]:
# No Copy
import numpy as np 
a = np.arange(6) 

print('Our array is:') 
print(a)  

print('Applying id() function:') 
print(id(a))  

print('a is assigned to b:') 
b = a #-> cung tro ve o nho
print(b)

print('b has same id():')
print(id(b))

print('Change shape of b:') 
b.shape = 3,2 
print(b)  

print('Shape of a also gets changed:')
print(a)

Our array is:
[0 1 2 3 4 5]
Applying id() function:
1651773256976
a is assigned to b:
[0 1 2 3 4 5]
b has same id():
1651773256976
Change shape of b:
[[0 1]
 [2 3]
 [4 5]]
Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]


In [19]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [18]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [9]:
# nditer()
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('ndim:', np.ndim(arr))
for x in np.nditer(arr):
  print(x)

ndim:  3
1
2
3
4
5
6
7
8


In [ ]:
Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to chang
the datatype of elementswhile iterating.

NumPy does not change the data type of the element in-place (where the element is in array)
so it needs some other space to perform this action, that extra space is called buffer,
and in order to enable it in nditer() we pass flags=['buffered'].


In [ ]:
# Optional
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)



In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


In [ ]:
K184060744 - Nguyễn Thị Hồng Nhung

In [ ]:
#Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating,
the ndenumerate() method can be used for those usecases.

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

print('\n')
print(type(idx))
print(type(x))

(0,) 1
(1,) 2
(2,) 3


<class 'tuple'>
<class 'numpy.int32'>


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr, '\n')
for idx, x in np.ndenumerate(arr):
  print(idx, x)

print('\n')
print(type(idx))
print(type(x))

[[1 2 3 4]
 [5 6 7 8]] 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


<class 'tuple'>
<class 'numpy.int32'>


In [3]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print('Original array is:')
print(a) 
print('id(a): ', id(a))
print('\n')  
   
print('Transpose of the original array is:') 
b = a.T # View : doi dong thanh cot, cot thanh dong
print (b)
print('id(b): ', id(b))
print('\n')
print('b.base:\n', b.base)
print('\n')

print('Modified array is:') 
for x in np.nditer(b): 
   print (x)

b[0,0] = 60
print('a:\n', a)
print('b:\n', b)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
id(a):  2253295180272


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
id(b):  2253295180464


b.base:
 [ 0  5 10 15 20 25 30 35 40 45 50 55]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55
a:
 [[60  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
b:
 [[60 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [4]:
# Iteration Order

import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

print('Transpose of the original array is:')
b = a.T
print(b)
print('\n')

print('Sorted in C-style order:')
c = b.copy(order = 'C') # by row
print(c)
for x in np.nditer(c):
   print(x)

print('\n')

print('Sorted in F-style order:')
c = b.copy(order = 'F') # by collumn
print(c)
for x in np.nditer(c):
   print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [5]:
# Modifying Array Values
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print('Modified array is:')
print(a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [6]:
# Optional
# External Loop

import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print('Original array is:')
print(a) 
print('\n')  

print('Modified array is:') 
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [7]:
# Broadcasting Iteration

import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print('First array is:') 
print(a)
print('\n')  

print('Second array is:') 
b = np.array([1, 2, 3, 4], dtype = int) 
print(b)  
print('\n') 

print('Modified array is:') 
for x,y in np.nditer([a,b]): 
   print("%d:%d" % (x,y))

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [ ]:
# Array Manipulation


In [ ]:
# Transpose Operations

In [8]:
a = np.arange(12).reshape(3,4) 
print(a)
print('a.base?:', a.base, '\n')
b = np.transpose(a)
print(b)
print('b.base?:', b.base)
print('\nb is a?:', b is a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.base?: [ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
b.base?: [ 0  1  2  3  4  5  6  7  8  9 10 11]

b is a?: False


In [9]:
a = np.arange(12).reshape(3,4) 
print(a, '\n')
b = a.T
print(b)
print('b.base?:', b.base)
print('\nb is a?:', b is a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
b.base?: [ 0  1  2  3  4  5  6  7  8  9 10 11]

b is a?: False


In [ ]:
# Joining Array
axis = 0: ngang, axis = 1 : đứng
# concatenate()

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2)) #arr = np.concatenate((arr1, arr2), axis =0)
# arr = np.concatenate((arr1, arr2), axis =1) error
print(arr)

[1 2 3 4 5 6]


In [12]:
import numpy as np

arr1 = np.array([1, 2, 3]).reshape(3,1)
print(arr1)
print('ndim arr1:', np.ndim(arr1))

arr2 = np.array([4, 6, 5]).reshape(3,1)
print(arr2)
print('ndim arr2:', np.ndim(arr2))

arr = np.concatenate((arr1, arr2)) #arr = np.concatenate((arr1, arr2), axis =0)

print('concatenate:\n', arr)


[[1]
 [2]
 [3]]
ndim arr1: 2
[[4]
 [6]
 [5]]
ndim arr2: 2
concatenate:
 [[1]
 [2]
 [3]
 [4]
 [6]
 [5]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3]).reshape(3,1)
print(arr1)
print('ndim arr1:', np.ndim(arr1))

arr2 = np.array([4, 5, 6]).reshape(3,1)
print(arr2)
print('ndim arr2:', np.ndim(arr2))

arr = np.concatenate((arr1, arr2), axis = 1)

print('concatenate:\n', arr)


In [13]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
print(arr1,'\n')

arr2 = np.array([[5, 6], [7, 8]])
print(arr2,'\n')

arr = np.concatenate((arr1, arr2), axis= 0)
print(arr)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
print(arr1,'\n')

arr2 = np.array([[5, 6], [7, 8]])
print(arr2,'\n')

arr = np.concatenate((arr1, arr2), axis= 1)
print(arr)



[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# stack(), ndim + 1 in result
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2)) # arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print('First Array:') 
print(a)
print('\n')
b = np.array([[5,6],[7,8]]) 

print('Second Array:') 
print(b)
print('\n')  

print('Stack the two arrays along axis 0:') 
print(np.stack((a,b),0)) #axis = 0
print('\n')  

print('Stack the two arrays along axis 1:')
print (np.stack((a,b),1)) #axis = 1

First Array:
[[1 2]
 [3 4]]


Second Array:
[[5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [26]:
# Stacking Along Rows
# hstack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2)) # No axis

print(arr)

[1 2 3 4 5 6]


In [27]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.hstack((arr1, arr2)) # No axis

print(arr1,'\n')
print(arr2,'\n')
print(arr)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Stacking Along Columns
# vstack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2)) # no axis

print(arr)

In [ ]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.vstack((arr1, arr2)) # no axis

print(arr1,'\n')
print(arr2,'\n')
print(arr)


In [ ]:
# Stacking Along Height (depth)
# dstack()
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))# No axis

print(arr)
print('ndim:', np.ndim(arr))

In [ ]:
# Splitting Array
 # array_split()

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)
#newarr = np.split(arr, 4) #error
print(newarr)

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr,'\n')
print(newarr[0])
print(newarr[1])
print(newarr[2])

newarr1 = np.array(newarr)
print('newarr1:\n', newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])] 

[1 2]
[3 4]
[5 6]
newarr1:
 [[1 2]
 [3 4]
 [5 6]]


### Thieu splitting 2D

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(arr,'\n')
print(newarr)

In [29]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr,'\n')
newarr = np.array_split(arr, 3, axis=1)

print(newarr)
print('newarr.shape: ', newarr[0].shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
newarr.shape:  (6, 1)


In [30]:
import numpy as np 
a = np.arange(9) 

print(a,'\n') 

print('split the array in 3 equal-sized subarrays:')
b = np.split(a,3) 
print(b,'\n') 

print('Split the array at positions indicated in 1-D array:')
b = np.split(a,[4,7])
print(b)

[0 1 2 3 4 5 6 7 8] 

split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])] 

Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [31]:
# hsplit()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [32]:
import numpy as np 
a = np.arange(16).reshape(4,4) 

print(a,'\n')  

b = np.hsplit(a,1) 
print(b,'\n')
print(b[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
import numpy as np 
a = np.arange(16).reshape(4,4) 

print(a,'\n')  

b = np.hsplit(a,2) 
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [ ]:
import numpy as np 
a = np.arange(16).reshape(4,4) 

print(a,'\n')  

# b = np.hsplit(a,3) # Error
b = np.hsplit(a,4)
print(b)

In [37]:
# vsplit()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr,'\n')
newarr = np.vsplit(arr, 2)

print(newarr,'\n')
print(newarr[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr,'\n')
newarr = np.vsplit(arr, 2)

print(newarr)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr,'\n')
newarr = np.vsplit(arr, 3)

print(newarr)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr,'\n')
#newarr = np.vsplit(arr, 5) #Error
newarr = np.vsplit(arr, 6)

print(newarr)

In [ ]:
# Adding / Removing Elements

In [38]:
# resize

import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print(a,'\n') 

print('The shape of first array:') 
print(a.shape, '\n') 
  
b = np.resize(a, (3,2)) 

print('Second array:') 
print(b,'\n') 

print('The shape of second array:') 
print(b.shape,'\n') 
  
# Observe that first row of a is repeated in b since size is bigger 

print('Resize the second array:')
b = np.resize(a,(3,3)) 
print(b)

[[1 2 3]
 [4 5 6]] 

The shape of first array:
(2, 3) 

Second array:
[[1 2]
 [3 4]
 [5 6]] 

The shape of second array:
(3, 2) 

Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [39]:
# append, Appends the values to the end of an array
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:\n',a,'\n')

print('Append elements to array:\n', np.append(a, [7,8,9]),'\n') 

print('Append elements along axis 0:\n', np.append(a, [[7,8,9]],axis = 0),'\n')

print('Append elements along axis 1:\n', np.append(a, [[5,5,5],[7,8,9]],axis = 1))

First array:
 [[1 2 3]
 [4 5 6]] 

Append elements to array:
 [1 2 3 4 5 6 7 8 9] 

Append elements along axis 0:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Append elements along axis 1:
 [[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [41]:
# insert, Inserts the values along the given axis before the given indices

import numpy as np 
a = np.array([[0,1],[2,3],[4,5]]) 

print('First array:\n', a, '\n')

print('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a,3,[11,12]), '\n')

print('Axis parameter passed. The values array is broadcast to match input array.')

print('Broadcast along axis 0:') 
print(np.insert(a,2,11,axis = 0), '\n') 

print('Broadcast along axis 1:')
print(np.insert(a,1,11,axis = 1))
print('******')
print(np.insert(a,1,[11,12,13],axis = 1))


First array:
 [[0 1]
 [2 3]
 [4 5]] 

Axis parameter not passed. The input array is flattened before insertion.
[ 0  1  2 11 12  3  4  5] 

Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 0  1]
 [ 2  3]
 [11 11]
 [ 4  5]] 

Broadcast along axis 1:
[[ 0 11  1]
 [ 2 11  3]
 [ 4 11  5]]
******
[[ 0 11  1]
 [ 2 12  3]
 [ 4 13  5]]


In [42]:
import numpy as np 
a = np.array([[0,1],[2,3],[4,5]]) 

print('First array:\n', a, '\n')

print('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a,3,[11,12]), '\n')

print('Axis parameter passed. The values array is broadcast to match input array.')

print('Broadcast along axis 0:') 
print(np.insert(a,2,[11, 12],axis = 0), '\n') 

print('Broadcast along axis 1:')
print(np.insert(a,1,[11, 12, 13],axis = 1))

First array:
 [[0 1]
 [2 3]
 [4 5]] 

Axis parameter not passed. The input array is flattened before insertion.
[ 0  1  2 11 12  3  4  5] 

Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 0  1]
 [ 2  3]
 [11 12]
 [ 4  5]] 

Broadcast along axis 1:
[[ 0 11  1]
 [ 2 12  3]
 [ 4 13  5]]


In [ ]:
# delete, Returns a new array with sub-arrays along an axis deleted
# Numpy.delete(arr, obj, axis)

arr: Input array

obj: Can be a slice, an integer or array of integers, indicating the subarray to be deleted from the input array

axis: The axis along which to delete the given subarray. If not given, arr is flattened

In [43]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print('First array:\n', a, '\n')

print('Array flattened before delete operation as axis not used:') 
print(np.delete(a,5), '\n') 

print('Column 2 deleted:')  
print(np.delete(a,1,axis = 1),'\n')
# print(np.delete(a,2,axis = 1),'\n')

print('Row 2 deleted:')  
print(np.delete(a,1,axis = 0),'\n')

print('A slice containing alternate values from array deleted:' )
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print(np.delete(a, np.s_[::2]))

First array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Array flattened before delete operation as axis not used:
[ 0  1  2  3  4  6  7  8  9 10 11] 

Column 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]] 

Row 2 deleted:
[[ 0  1  2  3]
 [ 8  9 10 11]] 

A slice containing alternate values from array deleted:
[ 2  4  6  8 10]


In [44]:
import numpy as np 
a = np.arange(12).reshape(3,4) 
a=np.transpose(a)

print('First array:\n', a, '\n')

print('Column 3 deleted:')  
print(np.delete(a,2,axis = 1),'\n')

First array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

Column 3 deleted:
[[0 4]
 [1 5]
 [2 6]
 [3 7]] 



In [45]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print('First array:\n', a, '\n')

print('Row 2 deleted:')  
print(np.delete(a,1,axis = 0),'\n')

First array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Row 2 deleted:
[[ 0  1  2  3]
 [ 8  9 10 11]] 



In [ ]:
K184060744 - Nguyễn Thị Hồng Nhung

In [ ]:
# unique, Finds the unique elements of an array
# numpy.unique(arr, return_index, return_inverse, return_counts)

1	
arr

The input array. Will be flattened if not 1-D array

2	
return_index

If True, returns the indices of elements in the input array

3	
return_inverse

If True, returns the indices of unique array, which can be used to reconstruct the input array

4	
return_counts

If True, returns the number of times the element in unique array appears in the original array



In [1]:
import numpy as np 
a = np.array([5,2,6,2,7,5,6,8,2,9]) 

print('First array:\n',a,'\n') 

print('Unique values of first array:')
u = np.unique(a) 
print(u, '\n') 

print('Unique array and Indices array:')
u,indices = np.unique(a, return_index = True) 
print(indices,'\n') 

print('We can see each number corresponds to index in original array:') 
print(a,'\n') 

print('Indices of unique array:')
u,indices_inverse = np.unique(a,return_inverse = True) 
print(u,'\n') 

print('Indices_inverse are:')
print(indices_inverse)

print('Reconstruct the original array using indices:') 
print(u[indices_inverse],'\n')

print('Return the count of repetitions of unique elements:')
u,counts = np.unique(a,return_counts = True) 
print(u) 
print(counts)
print(u.base)

First array:
 [5 2 6 2 7 5 6 8 2 9] 

Unique values of first array:
[2 5 6 7 8 9] 

Unique array and Indices array:
[1 0 2 4 7 9] 

We can see each number corresponds to index in original array:
[5 2 6 2 7 5 6 8 2 9] 

Indices of unique array:
[2 5 6 7 8 9] 

Indices_inverse are:
[1 0 2 0 3 1 2 4 0 5]
Reconstruct the original array using indices:
[5 2 6 2 7 5 6 8 2 9] 

Return the count of repetitions of unique elements:
[2 5 6 7 8 9]
[3 2 2 1 1 1]
None


In [ ]:
# Searching Arrays

In [2]:
# where(), return the indexes that get a match
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [5]:
import numpy as np 
x = np.arange(9).reshape(3, 3) 

print('x:\n',x)

print('Indices of elements > 3') 
y = np.where(x > 3) 
print(y)

print('Use these indices to get elements satisfying the condition')
print(x[y])

x:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Indices of elements > 3
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
Use these indices to get elements satisfying the condition
[4 5 6 7 8]


In [6]:
# extract() function returns the elements satisfying any condition
import numpy as np 
x = np.arange(9).reshape(3, 3) 

print('x:\n',x)

# define a condition 
condition = np.mod(x,2) == 0 

print('Element-wise value of condition\n', condition) 

print('Extract elements using condition')
print(np.extract(condition, x))

x:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Element-wise value of condition
 [[ True False  True]
 [False  True False]
 [ True False  True]]
Extract elements using condition
[0 2 4 6 8]


In [7]:
# nonzero() function returns the indices of non-zero elements in the input array
import numpy as np 
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 

print('a:\n',a,'\n')

print('Applying nonzero() function:') 
b = np.nonzero(a)
print(b)
print(a[b])

a:
 [[30 40  0]
 [ 0 20 10]
 [50  0 60]] 

Applying nonzero() function:
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))
[30 40 20 10 50 60]


In [8]:
# numpy.argmax() and numpy.argmin()
# These two functions return the indices of maximum and minimum elements
# respectively along the given axis.

import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print('a:\n',a,'\n')

print('Applying argmax() function:') 
print (np.argmax(a),'\n') 

print('Index of maximum number in flattened array') 
print(a.flatten(),'\n') 

print('Array containing indices of maximum a
      
      
      long axis 0:') 
maxindex = np.argmax(a, axis = 0) 
print(maxindex, '\n')  

print('Array containing indices of maximum along axis 1:') 
maxindex = np.argmax(a, axis = 1) 
print(maxindex,'\n')  

print('Applying argmin() function:')
minindex = np.argmin(a) 
print(minindex, '\n')  
   
print('Flattened array:') 
print(a.flatten()[minindex], '\n')  

print('Flattened array along axis 0:') 
minindex = np.argmin(a, axis = 0) 
print(minindex,'\n')

print('Flattened array along axis 1:') 
minindex = np.argmin(a, axis = 1) 
print(minindex)

a:
 [[30 40 70]
 [80 20 10]
 [50 90 60]] 

Applying argmax() function:
7 

Index of maximum number in flattened array
[30 40 70 80 20 10 50 90 60] 

Array containing indices of maximum along axis 0:
[1 2 0] 

Array containing indices of maximum along axis 1:
[2 0 1] 

Applying argmin() function:
5 

Flattened array:
10 

Flattened array along axis 0:
[0 1 1] 

Flattened array along axis 1:
[0 2 0]


In [26]:
# searchsorted(), performs a binary search in the array, 
# and returns the index where the specified value would be inserted to maintain the search order.
import numpy as np

arr = np.array([6, 7, 8, 9])
# arr = np.array([6, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

# The number 7 should be inserted on index 1 to remain the sort order.

# The method starts the search from the left and returns the first index 
# where the number 7 is no longer larger than the next value.

1


In [10]:
# Search From the Right Side
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)
# The number 7 should be inserted on index 2 to remain the sort order.

# The method starts the search from the right and returns the first index
# where the number 7 is no longer less than the next value.

2


In [11]:
# Multiple Values
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

# The return value is an array: [1 2 3] containing the three indexes
# where 2, 4, 6 would be inserted in the original array to maintain the order.

[1 2 3]


In [ ]:
# Sorting Arrays

In [12]:
# sort()
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [13]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [14]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [15]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
numpy.sort(a, axis, kind, order)
1	
a

Array to be sorted

2	
axis

The axis along which the array is to be sorted. If none, the array is flattened, sorting on the last axis

3	
kind (‘quicksort’, ‘mergesort’, ‘heapsort’)

Default is quicksort

4	
order

If the array contains fields, the order of fields to be sorted



In [16]:
import numpy as np  
a = np.array([[3,7],[9,1]]) 

print('a:\n', a, '\n') 

print('Applying sort() function:', a, '\n') 
  
print('Sort along axis 0:') 
print(np.sort(a, axis = 0), '\n') #Theo cột (axis = 0)

# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",27),("anil",25),("ravi", 17), ("raju",21)], dtype = dt) 

print('Our array is:\n',a,'\n') 

print('Order by name, then by age:') 
print(np.sort(a, order = ['name', 'age']))

a:
 [[3 7]
 [9 1]] 

Applying sort() function: [[3 7]
 [9 1]] 

Sort along axis 0:
[[3 1]
 [9 7]] 

Our array is:
 [(b'raju', 27) (b'anil', 25) (b'ravi', 17) (b'raju', 21)] 

Order by name, then by age:
[(b'anil', 25) (b'raju', 21) (b'raju', 27) (b'ravi', 17)]


In [17]:
# numpy.argsort() function performs an indirect sort on input array, 
# along the given axis and using a specified kind of sort to return the array of indices of data.
# This indices array is used to construct the sorted array

import numpy as np 
x = np.array([3, 1, 2]) 

print('Our array is:\n', x, '\n') 

print('Applying argsort() to x:') 
y = np.argsort(x) 
print(y,'\n') 

print('Reconstruct original array in sorted order:') 
print(x[y],'\n') 

print('Reconstruct the original array using loop:')
for i in y: 
   print(x[i])

Our array is:
 [3 1 2] 

Applying argsort() to x:
[1 2 0] 

Reconstruct original array in sorted order:
[1 2 3] 

Reconstruct the original array using loop:
1
2
3


In [18]:
# lexsort()
# function performs an indirect sort using a sequence of keys.
# The keys can be seen as a column in a spreadsheet.
# The function returns an array of indices, using which the sorted data can be obtained.
# Note, that the last key happens to be the primary key of sort
import numpy as np 

nm = ('raju','anil','raju','amar') 
dv = ('s.y.', 's.y.', 'f.y.', 'f.y.') 
ind = np.lexsort((dv,nm)) 

print('Applying lexsort() function:')
print(ind, '\n') 

print('Use this index to get sorted data:')
print([nm[i] + ", " + dv[i] for i in ind])

Applying lexsort() function:
[3 1 2 0] 

Use this index to get sorted data:
['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'raju, s.y.']


In [19]:
# Filtering Arrays
# Getting some elements out of an existing array and creating a new array out of them
# you filter an array using a boolean index list

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [20]:
# Creating the Filter Array

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [22]:
# Creating Filter Directly From Array
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [24]:
a = np.array([[0, 1, 7, 0],
              [3, 0, 2, 19]])
print(np.count_nonzero(a),'\n')

print(np.count_nonzero(a, axis=0),'\n')

print(np.count_nonzero(a, axis=1),'\n')

print(np.count_nonzero(a, axis=1, keepdims=True))


5 

[1 1 2 1] 

[2 3] 

[[2]
 [3]]
