In [1]:
# 1/
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a,'\n')

print('The items in the last column are:')
print(a[...,2]) 

print('The items in the last row are:')
print(a[2,...]) 

print('Column 0, column 2:')
print(a[0:3, [0,2]])

print('Row 0, row 2:')
print(a[[0,2], 0:3])

[[1 2 3]
 [3 4 5]
 [4 5 6]] 

The items in the last column are:
[3 5 6]
The items in the last row are:
[4 5 6]
Column 0, column 2:
[[1 3]
 [3 5]
 [4 6]]
Row 0, row 2:
[[1 2 3]
 [4 5 6]]


In [58]:
# 2/ 
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x,'\n')

# Dùng Array of Indices để xuất ra các phần tử: x[0,1], x[1,0], x[2,1]
y = x[[0,1,2], [1,0,1]] 
print(y)

[[1 2]
 [3 4]
 [5 6]] 

[2 3 6]


In [3]:
# 3/
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:\n', x,'\n') 

# Xuất ra màn hình như bên dưới: 
y = np.array([[x[1,0],x[0,1]], [x[2,1],x[3,2]]])

print('The output:') 
print(y)

Our array is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

The output:
[[ 3  1]
 [ 7 11]]


In [4]:
# 4/
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:')
print(x) 
print('\n')  
 
print('The items greater or equal to 6 are:')
print(x[x >= 6])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater or equal to 6 are:
[ 6  7  8  9 10 11]


In [5]:
# 5/
import numpy as np 

'''
Lập data type cho cổ phiếu gồm:
code kiểu dữ liệu: S5
quantity kiểu dữ liệu: i4
askprice kiểu dữ liệu: f4
'''
stockdtype = np.dtype([('Code','S5'), ('Quantity', 'i4'), ('AskPrice', 'f4')]) 

'''
Nhập dữ liệu các chứng khoán:
Code: "TCB"
Quantity : 1200,
AskPrice : 39.6

Code: "MSN"
Quantity : 2350,
AskPrice : 87.6

Code: POW
Quantity : 980,
AskPrice : 13.45
'''
stockarr = np.array([('TCB', 1200, 39.6), ('MSN', 2350, 87.6), ('POW', 980, 13.45)], dtype = stockdtype) 

print(stocktype)
print(stockarr)
#Xuất ra danh sách các code
print(stockarr['Code'])

[('code', 'S5'), ('quantity', '<u8'), ('askprice', '<f4')]
[(b'TCB', 1200, 39.6 ) (b'MSN', 2350, 87.6 ) (b'POW',  980, 13.45)]
[b'TCB' b'MSN' b'POW']


In [9]:
# 6/
import numpy as np 
arr = np.array(range(24))
print('arr:\n', arr,'\n')

#kích thước (4,6),  có base là arr
newarr = arr.reshape(4,6)

print('newarr:\n',newarr, '\n')
print('newarr.base;\n', newarr.base)

arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

newarr:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

newarr.base;
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [59]:
# 7/
import numpy as np 
arr = np.array(range(24))
print('arr:\n', arr,'\n')

#Deep copy từ arr, kích thước (4,6), đổi phần tử đầu tiên thành 24
dc = arr.copy()
dc[0] = 24
dc.shape = (4,6)
print('\n dc:\n',dc)
print('arr:\n',arr)
print('dc.base:\n',dc.base)
print('dc is arr:',dc is arr)

#Shallow copy từ arr, kích thước (3,8), đổi phần tử đầu tiên thành 30
sc = arr.view()
sc[0] = 30
sc.shape = (3,8)
print('\n sc:\n',sc)
print ('arr:\n',arr)
print('sc.base:',sc.base)
print('sc is arr:',sc is arr)

#Trỏ tới vùng dữ liệu của arr, kích thước (6,4), đổi phần tử đầu tiên thành 40
nc = arr
nc[0] = 40
nc.shape = (6,4)
print('\n nc:\n',nc)
print ('arr:\n',arr)
print('nc.base:',nc.base)
print('nc is arr:',nc is arr)

# Chỉnh lại code để xuất ra rõ ràng

arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 


 dc:
 [[24  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
dc.base:
 None
dc is arr: False

 sc:
 [[30  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
arr:
 [30  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
sc.base: [30  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
sc is arr: False

 nc:
 [[40  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
arr:
 [[40  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
nc.base: None
nc is arr: True


In [57]:
# 8/
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

for x in np.nditer(arr[:,1::2]):
  print(x)

2
4
7
9
12
14


In [60]:
# 9/ 
import numpy as np
a = np.arange(1,21)
a = a.reshape(4,5)

print('Original array is:\n', a, '\n')

for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = x*x
print('Modified array is:')
print(a)

Original array is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

Modified array is:
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


In [50]:
# 10/ tạo a, b dùng arange và reshape
import numpy as np 

a = np.arange(1,24,2) 
a = a.reshape(3,4)
print('a:\n',a, '\n')
b = np.arange(2,25,2) 
b = b.reshape(3,4) 
print('b:\n',b, '\n')

c = np.arange(3,48,4)
c = c.reshape(3,4)
print('c:\n',c)


a:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]] 

b:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]] 

c:
 [[ 3  7 11 15]
 [19 23 27 31]
 [35 39 43 47]]
