In [66]:
# 1/ 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print('Original:') 
print(arr, '\n')

del_3 = np.delete(arr, 2, axis = 0)
a = np.array(del_3)
del_5 = np.delete(a, 3, axis = 0)
print('Delete row 3 and 5:')  
print(del_5, '\n')

print('Delete row 2, 4, 6 (use slice):')  
print(arr[0:5:2], '\n')


del_last_col = np.delete(arr, 2, axis = 1)
del_last_row = np.delete(del_last_col, 5, axis = 0)
print('Delete the last column:')  
print(del_last_row)

Original:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

Delete row 3 and 5:
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [16 17 18]] 

Delete row 2, 4, 6 (use slice):
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]] 

Delete the last column:
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]]


In [33]:
#2/
import numpy as np 
arr = np.array([[3,9,6],[9,7,3],[6,8,9]]) 

print('Array:\n',arr,'\n') 

new = np.unique(arr)  
print('Xóa phần tử trùng lắp:','\n',new,'\n')

new,indices_inverse = np.unique(arr,return_inverse = True) 
print('Phục hồi array:','\n', new[indices_inverse].reshape(3, 3),'\n')

print('Số lần xuất hiện của các giá trị:')
new,counts = np.unique(arr,return_counts = True) 
print(new, "xuất hiện") 
print(counts, "lần")

Array:
 [[3 9 6]
 [9 7 3]
 [6 8 9]] 

Xóa phần tử trùng lắp: 
 [3 6 7 8 9] 

Phục hồi array: 
 [[3 9 6]
 [9 7 3]
 [6 8 9]] 

Số lần xuất hiện của các giá trị:
[3 6 7 8 9] xuất hiện
[2 2 1 1 3] lần


In [15]:
#3/
import numpy as np 
arr = np.array([[3,9,6,7],[9,7,3,4],[6,8,9,12]])
print('Array:\n',arr,'\n') 

print('Các số chia hết cho 3:')
filter_arr = arr % 3 == 0
newarr = arr[filter_arr]
u = np.unique(newarr)
print(u)

Array:
 [[ 3  9  6  7]
 [ 9  7  3  4]
 [ 6  8  9 12]] 

Các số chia hết cho 3:
[ 3  6  9 12]


In [60]:
#4/

import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,8,9,12]])
print('Array:\n',arr,'\n') 

print('Số lớn nhất của mỗi dòng:')
maxindex = np.max(arr, axis = 1) 
print(maxindex,'\n') 

print('Số nhỏ nhất của mỗi cột:')
minindex = np.min(arr, axis = 0) 
print(minindex,'\n')

Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6  8  9 12]] 

Số lớn nhất của mỗi dòng:
[ 9 10 12] 

Số nhỏ nhất của mỗi cột:
[3 7 3 4] 



In [8]:
# 5/

import numpy as np
arr = np.array([6,3,5,9,2,4,7, 10, 15,14,16,18,19])
print('Array:\n', arr, '\n')

new_arr = np.sort(arr)
print('Sorted array:\n', new_arr,'\n')

number = int(input('Nhập 1 số bất kỳ từ 1->20: ')) # lưu ý :nhập số lớn hơn 10, nhỏ hơn 19, ví dụ nhập số 13

x = np.searchsorted(new_arr, number)

a = np.insert(new_arr, x, number)

print('\nChèn number vào array mà không đổi thứ tự:\n',a)

Array:
 [ 6  3  5  9  2  4  7 10 15 14 16 18 19] 

Sorted array:
[ 2  3  4  5  6  7  9 10 14 15 16 18 19] 

Nhập 1 số bất kỳ từ 1->20: 13

Chèn number vào array mà không đổi thứ tự:
[ 2  3  4  5  6  7  9 10 13 14 15 16 18 19]


In [6]:
#6
import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,12,8,9]])
print('Array:\n',arr,'\n')
print('Sorted arr:')
print(np.sort(arr,axis=None).reshape(3,4))
print('Sorted arr theo từng dòng:') 
print(np.sort(arr, axis = 1), '\n')
print('Sorted arr theo từng cột:') 
print(np.sort(arr, axis = 0), '\n')

Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6 12  8  9]] 

Sorted arr:
[[ 3  3  4  6]
 [ 6  7  7  8]
 [ 9  9 10 12]] 

Sorted arr theo từng dòng:
[[ 3  6  7  9]
 [ 3  4  7 10]
 [ 6  8  9 12]] 

Sorted arr theo từng cột:
[[ 3  7  3  4]
 [ 6  9  6  7]
 [10 12  8  9]] 



In [2]:
import numpy as np
memberdtype = np.dtype([('HoTen', 'S10'),('TinhThanh', 'S10'),("ThuNhap",'i4')]) 
memberarr= np.array([("Ngoc","Binh Duong",2000000),("Van Anh","Vung Tau",1000000),("Kien","Da Lat",1500000),("Nhung","Vung Tau",30000000),("Toan","Binh Thuan",18000000)], dtype = memberdtype) 
print('Sắp xếp theo TinhThanh, HoTen, Thu Nhap')
print(np.sort(memberarr, order = ['TinhThanh', 'HoTen','ThuNhap']))

Sắp xếp theo TinhThanh, HoTen, Thu Nhap
[(b'Ngoc', b'Binh Duong',  2000000) (b'Toan', b'Binh Thuan', 18000000)
 (b'Kien', b'Da Lat',  1500000) (b'Nhung', b'Vung Tau', 30000000)
 (b'Van Anh', b'Vung Tau',  1000000)]


In [2]:
#8
#8
import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,12,8,9]])
print('Array:\n',arr,'\n')
print('x (indices):\n',np.argsort(arr,axis=None),'\n')
print('Sorted array:\n',np.sort(arr,axis=None).reshape(3, 4),'\n')

Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6 12  8  9]] 

x (indices):
 [ 0  6  7  2  8  3  5 10  1 11  4  9] 

Sorted array:
 [[ 3  3  4  6]
 [ 6  7  7  8]
 [ 9  9 10 12]] 

