In [1]:
# 1/
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a,'\n')

print('The items in the last column are:')
#??????????

print('The items in the last row are:')
#??????????

print('Column 0, column 2:')
#??????????

print('Row 0, row 2:')
#??????????

[[1 2 3]
 [3 4 5]
 [4 5 6]] 

The items in the last column are:
[3 5 6]
The items in the last row are:
[4 5 6]
Column 0, column 2:
[[1 3]
 [3 5]
 [4 6]]
Row 0, row 2:
[[1 2 3]
 [4 5 6]]


In [2]:
# 2/ 
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x,'\n')

# Dùng Array of Indices để xuất ra các phần tử: x[0,1], x[1,0], x[2,1]
#??????????

[[1 2]
 [3 4]
 [5 6]] 

[2 3 6]


In [3]:
# 3/
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:\n',x,'\n') 

# Xuất ra màn hình như bên dưới: 
#??????????

print('The output:') 
print(y)

Our array is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

The output:
[[ 3  1]
 [ 7 11]]


In [4]:
# 4/
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:')
print(x) 
print('\n')  
 
print('The items greater or equal to 6 are:')
#???????

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater or equal to 6 are:
[ 6  7  8  9 10 11]


In [5]:
# 5/
import numpy as np 

'''
Lập data type cho cổ phiếu gồm:
code kiểu dữ liệu: S5
quantity kiểu dữ liệu: i4
askprice kiểu dữ liệu: f4
'''
stockdtype = #?????

'''
Nhập dữ liệu các chứng khoán:
Code: "TCB"
Quantity : 1200,
AskPrice : 39.6

Code: "MSN"
Quantity : 2350,
AskPrice : 87.6

Code: POW
Quantity : 980,
AskPrice : 13.45
'''
stockarr = #?????

print(stocktype)
print(stockarr)
#Xuất ra danh sách các code
#????

[('code', 'S5'), ('quantity', '<u8'), ('askprice', '<f4')]
[(b'TCB', 1200, 39.6 ) (b'MSN', 2350, 87.6 ) (b'POW',  980, 13.45)]
[b'TCB' b'MSN' b'POW']


In [6]:
# 6/
import numpy as np 
arr = np.array(range(24))
print('arr:\n', arr,'\n')

newarr = #????? kích thước (4,6),  có base là arr

print('newarr:\n', newarr, '\n')
print('newarr.base;\n', newarr.base)

arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

newarr:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

newarr.base;
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
# 7/
import numpy as np 
arr = np.array(range(24))
print('arr:\n', arr,'\n')

dc = #???? Deep copy từ arr, kích thước (4,6), đổi phần tử đầu tiên thành 24
print(dc)
print (arr)
print(dc.base)
print(dc is arr)

sc = #???? Shallow copy từ arr, kích thước (3,8), đổi phần tử đầu tiên thành 30
print(sc)
print (arr)
print(sc.base)
print(sc is arr)

nc = arr#???? Trỏ tới vùng dữ liệu của arr, kích thước (6,4), đổi phần tử đầu tiên thành 40

print(nc)
print (arr)
print(nc.base)
print(nc is arr)

# Chỉnh lại code để xuất ra rõ ràng

arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

dc:
 [[24  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
dc.base:  [24  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
dc is arr:  False 

sc:
 [[30  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
arr:
 [30  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
sc.base:  [30  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
sc is arr:  False 

nc:
 [[40  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
arr:
 [[40  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
nc.base:  None
nc is arr:  True 



In [8]:
# 8/
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

# Xuất ra như màn hình dưới
# ??????

2
4
7
9
12
14


In [9]:
# 9/ 
import numpy as np
a = np.arange(1,21)
a = a.reshape(4,5)

print('Original array is:\n', a, '\n')

# ???????

print('Modified array is:')
print(a)

Original array is:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

Modified array is:
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


In [10]:
# 10/ tạo a, b dùng arange và reshape
import numpy as np 

#?????
print('a:\n',a, '\n')

#??????
print('b:\n',b, '\n')

# ?????
print ('c:\n', c)

a:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]] 

b:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]] 

c:
 [[ 3  7 11 15]
 [19 23 27 31]
 [35 39 43 47]]
