In [15]:
# 1/ 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr, '\n')

print('Delete row 3 and 5:')  
?????

print('Delete row 2,4,6 (use slice):')  
?????

print('Delete the last column:')  
?????

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

Delete row 3 and 5:
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [16 17 18]] 

Delete row 2,4,6 (use slice):
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]] 

Delete the last column:
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]
 [16 17]]


In [51]:
# 2/

import numpy as np 
arr = np.array([[3,9,6],[9,7,3],[6,8,9]]) 

print('Array:\n',arr,'\n') 

print('Xóa phần tử trùng lắp:')
?????

del(arr)

print('Phục hồi array:')
?????

print('Số lần xuất hiện của các giá trị:')
?????


Array:
 [[3 9 6]
 [9 7 3]
 [6 8 9]] 

Xóa phần tử trùng lắp:
[3 6 7 8 9] 

Phục hồi array:
[[3 9 6]
 [9 7 3]
 [6 8 9]] 

Số lần xuất hiện của các giá trị:
[3 6 7 8 9] xuất hiện
[2 2 1 1 3] lần


In [59]:
#3/

import numpy as np 
arr = np.array([[3,9,6,7],[9,7,3,4],[6,8,9,12]])
print('Array:\n',arr,'\n') 

print('Các số chia hết cho 3:')
?????

Array:
 [[ 3  9  6  7]
 [ 9  7  3  4]
 [ 6  8  9 12]] 

Các số chia hết cho 3:
[ 3  6  9 12]


In [70]:
#4/

import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,8,9,12]])
print('Array:\n',arr,'\n') 

print('Số lớn nhất của mỗi dòng:')
?????

print('Số nhỏ nhất của mỗi cột:')
?????


Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6  8  9 12]] 

Số lớn nhất của mỗi dòng:
[ 9 10 12] 

Số nhỏ nhất của mỗi cột:
[3 7 3 4]


In [8]:
# 5/

import numpy as np
arr = np.array([6,3,5,9,2,4,7, 10, 15,14,16,18,19])
print('Array:\n', arr, '\n')

print('Sorted array:')
?????

number = input('Nhập 1 số bất kỳ từ 1->20: ')) # lưu ý :nhập số lớn hơn 10, nhỏ hơn 19, ví dụ nhập số 13

print('\nChèn number vào array mà không đổi thứ tự:')
?????

Array:
 [ 6  3  5  9  2  4  7 10 15 14 16 18 19] 

Sorted array:
[ 2  3  4  5  6  7  9 10 14 15 16 18 19] 

Nhập 1 số bất kỳ từ 1->20: 13

Chèn number vào array mà không đổi thứ tự:
[ 2  3  4  5  6  7  9 10 13 14 15 16 18 19]


In [6]:
# 6/
import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,12,8,9]])
print('Array:\n',arr,'\n')

print('Sorted arr:')
?????

print('Sorted arr theo từng dòng:') 
????? 

print('Sorted arr theo từng cột:') 
????? 

Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6 12  8  9]] 

Sorted arr:
[[ 3  3  4  6]
 [ 6  7  7  8]
 [ 9  9 10 12]] 

Sorted arr theo từng dòng:
[[ 3  6  7  9]
 [ 3  4  7 10]
 [ 6  8  9 12]] 

Sorted arr theo từng cột:
[[ 3  7  3  4]
 [ 6  9  6  7]
 [10 12  8  9]] 



In [ ]:
# 7/

import numpy as np 

'''
Lập data type cho member gồm:
HoTen kiểu dữ liệu: S10
TinhThanh kiểu dữ liệu: S10
ThuNhap kiểu dữ liệu: i4
'''
memberdtype = ????

'''
Nhập dữ liêu với 5 người (nhập tùy ý)
'''
memberarr = ???

print('Sắp xếp theo TinhThanh, HoTen, Thu Nhap ')
?????

In [1]:
# 8/
import numpy as np 
arr = np.array([[3,9,6,7],[10,7,3,4],[6,12,8,9]])
print('Array:\n',arr,'\n')

x = ?????
?????


Array:
 [[ 3  9  6  7]
 [10  7  3  4]
 [ 6 12  8  9]] 

x (indices):
 [ 0  6  7  2  8  3  5 10  1 11  4  9] 

Sorted array:
 [[ 3  3  4  6]
 [ 6  7  7  8]
 [ 9  9 10 12]] 

