In [7]:
#1/ numpy ufunc
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([7, 8, 9, 10, 11, 12])
arr3 = np.array([13, 14, 5, 16, 17, 18])

newarr = ????

print(newarr)

[21 24 17 30 33 36]


In [13]:
#2/  y = a*x + b
import numpy as np

x = np.array([1, 2, 3, 4])

????

a = 2
b = 3
y = ????

print(y)
????

[5 7 9 11]
<class 'numpy.ufunc'>


In [20]:
#3/ min, max 
import numpy as np

arr1 = np.array([10, 7, 30, 40, 2, 60])
arr2 = np.array([3, 20, 9, 8, 50, 33])

????

amin, amax = ????

print('array min:', amin,'\n')
print('array max:', amax,'\n')

print('findminmax:', ????)

array min: [3 7 9 8 2 33] 

array max: [10 20 30 40 50 60] 

findminmax: <class 'numpy.ufunc'>


In [26]:
#4/

import numpy as np 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a:\n', a,'\n')

b = np.array([1,2,3])

print('Cộng cột a và b:\n')

????

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Cộng cột a và b:

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [32]:
#5/
import numpy as np

a = np.array([-4.356, 2.738])

print('Làm tròn 1 chữ số sau phần thập phân:', ????,'\n')
print('Lây phần nguyên trên', ????,'\n')
print('Lấy phần nguyên dưới:', ????,'\n')
print('Lấy phần nguyên gần 0 nhất:', ????,'\n')

Làm tròn 1 chữ số sau phần thập phân: [-4.4  2.7] 

Lây phần nguyên trên [-4.  3.] 

Lấy phần nguyên dưới: [-5.  2.] 

Lấy phần nguyên gần 0 nhất: [-4.  2.] 



In [1]:
# 6/ Tính log6(x)

import numpy as np

x = np.array([6, 36, 216])

????

[1.0 2.0 3.0000000000000004]


In [2]:
#7/ #sum, cumsum
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('a:\n',a,'\n')
print('b:\n',b,'\n')

newarr1 = ????
print('newarr:\n', newarr1,'\n')

newarr2 = ????
print('newarr2:\n', newarr2, '\n')

x = np.array([[1, 2], [3, 4]])
newarr3 = ????
print('newarr3:\n', newarr3)

a:
 [[1 2]
 [3 4]] 

b:
 [[5 6]
 [7 8]] 

newarr:
 [[ 6  8]
 [10 12]] 

newarr2:
 [[ 4  6]
 [12 14]] 

newarr3:
 [[ 1  3]
 [ 6 10]]


In [56]:
# 8/ 
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

newarr = ????
newarr1 = ????
newarr2 = ????

print('newarr:', newarr, '\n')
print('newarr1:', newarr1, '\n')
print('newarr2:', newarr2, '\n')


newarr: 24 

newarr1: [ 2 12] 

newarr2: [3 8] 



In [57]:
#9/

import numpy as np

arr = np.array([8, 32, 36, 16])

print('Bội số chung nhỏ nhât:', ???? ,'\n')
print('Ước số chung lớn nhất:', ???? ,'\n')

Bội số chung nhỏ nhât: 288 

Ước số chung lớn nhất: 4 



In [62]:
#10/
import numpy as np

arr1 = np.array([4, 6, 2, 3,  4])
arr2 = np.array([4, 6, 2, 1, 6])

print('Phần tử riêng của arr1 và arr2:', ????)
print('Phần tử chung:', ????)
print('Phần tử trong arr1 không có trong arr2:',????)

Phần tử riêng của arr1 và arr2: [1 3]
Phần tử chung: [2 4 6]
Phần tử trong arr1 không có trong arr2: [3]
